@startuml
class User {
  isAdmin: boolean
  email: string
  password: string
  phone: string
  totalHoursApproved: number
  approvedHours: Array<LoggedHour._id::string>
  pendingHours: Array<LoggedHour._id::string>
}

class Hour {
  start_time: date
  end_time: date
  verified: boolean
  verifiedBy: User._id::string
  userId: User._id::string
  eventName: string
  eventDescription: string
}

class PendingHours{
  hour: Hours::ObjectId
}


@enduml